name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login Dockerhub
      
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}      

    - name: Build the Docker image
      run: docker build --build-arg OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} SECRET_KEY=${{secrets.SECRET_KEY}} DB_HOST=${{secrets.DB_HOST}} DB_USER=${{secrets.DB_USER}} DB_PASSWORD=${{secrets.DB_PASSWORD}} -t mongol .

    - name: taging
      run: docker tag mongol:latest ${{ secrets.DOCKERHUB_USERNAME }}/mongol:latest

    - name: Push to Dockerhub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/mongol:latest
    
  deploy:

    runs-on: self-hosted
    needs: build

    steps:
    - name: Pull Docker image
      run: sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/mongol:latest
    - name: Delete Old docker container
      run: sudo docker rm -f mongol-container || true
    - name: Run Docker Container
      run: sudo docker run -d -p 3000:3000 --name mongol-container ${{ secrets.DOCKERHUB_USERNAME }}/mongol